#!/usr/bin/env php
<?php

/**
 * SPRITE.IO
 * 
 * @author  James Levi Crisostomo
 */

// Include the composer autoloader. 
if(file_exists('vendor/autoload.php'))
{
    require 'vendor/autoload.php';
}

// Create new sprite object each time a command
// is executed from the CLI.
$sprite = \Sprite\Sprite::init($argv, __DIR__);

// Execute sprite program.
$sprite->exec();

// Terminate sprite program.
$sprite->terminate();